/* ═══════════════════════════════════════════════════
   SmartFarm — All Static Data
   ═══════════════════════════════════════════════════ */

const CROPS_DATA = [
  { id:'rice',       name:'Rice',        emoji:'🌾', season:'Kharif',  duration:120, waterNeed:'High',   soilType:'Clay/Loamy',  yieldPerAcre:'20-25 qtl', spacing:'20×15 cm', npk:{n:120,p:60,k:60},  description:'Staple food crop of India grown in flooded paddies. Requires warm humid climate.', tips:['Maintain 5cm water level during tillering','Use SRI method to save 30% water','Transplant 21-day seedlings for best yield','Apply Zinc @ 25kg/ha in deficient soils'], pests:['Brown Planthopper','Stem Borer','Blast'], diseases:['Bacterial Blight','Sheath Blight','Tungro']},
  { id:'wheat',      name:'Wheat',       emoji:'🌻', season:'Rabi',    duration:120, waterNeed:'Medium', soilType:'Loamy',       yieldPerAcre:'15-20 qtl', spacing:'22.5 cm rows', npk:{n:120,p:60,k:40}, description:'Most important rabi crop of India. Grown extensively in Punjab, Haryana, UP.', tips:['Sow between Nov 1-25 for best yield','Apply first irrigation at crown root stage (21 days)','Use disease-resistant varieties like HD-2967','Apply weedicide Isoproturon @ 1kg/ha at 30-35 days'], pests:['Aphid','Brown Wheat Mite','Army Worm'], diseases:['Yellow Rust','Loose Smut','Karnal Bunt']},
  { id:'maize',      name:'Maize',       emoji:'🌽', season:'Kharif',  duration:90,  waterNeed:'Medium', soilType:'Loamy/Sandy', yieldPerAcre:'20-25 qtl', spacing:'60×20 cm', npk:{n:150,p:75,k:50},  description:'Third most important cereal crop. Used for food, feed, and industrial purposes.', tips:['Earth-up at 30 days to support stalks','Apply nitrogen in 3 splits: basal, 30 days, 50 days','Ensure proper drainage to prevent water-logging','Intercrop with legumes for soil health'], pests:['Fall Army Worm','Stem Borer','Aphid'], diseases:['Downy Mildew','Blight','Smut']},
  { id:'cotton',     name:'Cotton',      emoji:'🌿', season:'Kharif',  duration:180, waterNeed:'Medium', soilType:'Black/Loamy', yieldPerAcre:'8-12 qtl',  spacing:'90×60 cm', npk:{n:100,p:50,k:50},  description:'White gold of India. Major cash crop grown in Maharashtra, Gujarat, Telangana.', tips:['Use Bt cotton varieties for bollworm management','Maintain square balance: N:P:K = 2:1:1','Apply growth regulator mepiquat at bud stage','Monitor pink bollworm traps from August'], pests:['Pink Bollworm','Whitefly','Thrips'], diseases:['Fusarium Wilt','Alternaria Blight','Leaf Curl Virus']},
  { id:'sugarcane',  name:'Sugarcane',   emoji:'🎋', season:'Annual',  duration:360, waterNeed:'Very High', soilType:'Loamy',    yieldPerAcre:'250-300 qtl',spacing:'90 cm rows', npk:{n:250,p:100,k:120},description:'Long duration cash crop with high income potential. Requires deep fertile soils.', tips:['Use single bud sets for planting','Apply Trichoderma with FYM at planting','Trash mulching conserves moisture and suppresses weeds','Propping and earthing-up prevents lodging'], pests:['Early Shoot Borer','Woolly Aphid','Pyrilla'], diseases:['Red Rot','Wilt','Grassy Shoot']},
  { id:'tomato',     name:'Tomato',      emoji:'🍅', season:'All year',duration:90,  waterNeed:'Medium', soilType:'Loamy/Sandy', yieldPerAcre:'80-100 qtl', spacing:'60×45 cm', npk:{n:100,p:60,k:80},  description:'Most important vegetable crop. High value with demand throughout the year.', tips:['Stake plants at 30-40 cm height','Remove suckers weekly for better fruiting','Use drip irrigation to prevent leaf wetness','Apply calcium foliar spray to prevent blossom end rot'], pests:['Fruit Borer','Whitefly','Aphid'], diseases:['Early Blight','Late Blight','Leaf Curl Virus']},
  { id:'potato',     name:'Potato',      emoji:'🥔', season:'Rabi',    duration:90,  waterNeed:'Medium', soilType:'Loamy/Sandy', yieldPerAcre:'80-100 qtl', spacing:'60×20 cm', npk:{n:120,p:100,k:120}, description:'Versatile vegetable and staple food. Important cash crop in UP, Punjab, West Bengal.', tips:['Plant certified disease-free seed tubers','Hilling at 25-30 days prevents greening','Irrigate lightly and frequently','Stop irrigation 2 weeks before harvest'], pests:['Potato Tuber Moth','Aphid','Cutworm'], diseases:['Late Blight','Early Blight','Common Scab']},
  { id:'onion',      name:'Onion',       emoji:'🧅', season:'Rabi',    duration:120, waterNeed:'Medium', soilType:'Loamy',       yieldPerAcre:'60-80 qtl',  spacing:'15×10 cm', npk:{n:80,p:50,k:50},   description:'Important bulb crop and foreign exchange earner. Grown across India year-round.', tips:['Transplant 6-8 week old seedlings','Apply sulphur to improve pungency','Stop irrigation 10 days before harvest','Cure bulbs in shade for 7-10 days'], pests:['Thrips','Onion Fly','Stem Nematode'], diseases:['Purple Blotch','Stemphylium Blight','Downy Mildew']},
  { id:'chilli',     name:'Chilli',      emoji:'🌶️', season:'Kharif', duration:150, waterNeed:'Medium', soilType:'Loamy',       yieldPerAcre:'10-15 qtl',  spacing:'45×30 cm', npk:{n:100,p:60,k:60},  description:'High-value spice crop with large domestic and export market demand.', tips:['Harden seedlings before transplanting','Mulch with black polythene to control weeds','Apply boron and calcium for fruit set','Use sticky yellow traps for thrips monitoring'], pests:['Thrips','Mites','Fruit Borer'], diseases:['Anthracnose','Phytophthora Blight','Leaf Curl Virus']},
  { id:'soybean',    name:'Soybean',     emoji:'🫘', season:'Kharif',  duration:100, waterNeed:'Medium', soilType:'Loamy/Black', yieldPerAcre:'10-15 qtl',  spacing:'45×5 cm',  npk:{n:30,p:60,k:40},   description:'Oilseed and protein crop. Fixes nitrogen and improves soil health.', tips:['Inoculate seeds with Rhizobium culture','Sow at moisture-sufficient time after monsoon onset','Avoid waterlogging — good drainage is essential','Harvest when 95% pods turn yellow-brown'], pests:['Girdle Beetle','Stem Fly','Pod Borer'], diseases:['Yellow Mosaic Virus','Anthracnose','Root Rot']},
  { id:'groundnut',  name:'Groundnut',   emoji:'🥜', season:'Kharif',  duration:110, waterNeed:'Medium', soilType:'Sandy Loam',  yieldPerAcre:'8-12 qtl',  spacing:'30×10 cm', npk:{n:20,p:40,k:40},   description:'Important oilseed crop providing edible oil and protein-rich cake for feed.', tips:['Apply Gypsum @ 500 kg/ha at peg initiation','Earthing-up when pegs start entering soil','Apply Rhizobium + PSB bio-fertilizers','Harvest before frost for good quality'], pests:['Leaf Miner','Thrips','White Grub'], diseases:['Tikka Leaf Spot','Bud Necrosis','Collar Rot']},
  { id:'mustard',    name:'Mustard',     emoji:'🌼', season:'Rabi',    duration:110, waterNeed:'Low',    soilType:'Loamy',       yieldPerAcre:'6-8 qtl',   spacing:'30×10 cm', npk:{n:80,p:40,k:40},   description:'Major oilseed rabi crop. Short duration with low input requirements.', tips:['Sow in Oct-Nov for best yield','Apply sulphur @ 40 kg/ha — essential for oil quality','One irrigation at branching + one at pod filling','Harvest at 75% pod maturity to avoid shattering'], pests:['Painted Bug','Aphid','Sawfly'], diseases:['White Rust','Alternaria Blight','Sclerotinia Rot']},
  { id:'jowar',      name:'Jowar (Sorghum)', emoji:'🌾', season:'Kharif', duration:115, waterNeed:'Low', soilType:'All types',   yieldPerAcre:'12-18 qtl', spacing:'45×15 cm', npk:{n:80,p:40,k:25},   description:'Drought-tolerant coarse cereal. Excellent for dryland farming areas.', tips:['Gap filling at 10-15 days after sowing','Apply FYM/compost for good yield','Spray carbaryl for shoot fly management','Harvest when grain moisture is 20-25%'], pests:['Shoot Fly','Stem Borer','Midge'], diseases:['Grain Mold','Downy Mildew','Anthracnose']},
  { id:'bajra',      name:'Bajra (Pearl Millet)', emoji:'🌾', season:'Kharif', duration:80, waterNeed:'Very Low', soilType:'Sandy',  yieldPerAcre:'10-14 qtl', spacing:'45×15 cm', npk:{n:60,p:30,k:15},   description:'Most drought-resistant cereal. Suited for arid and semi-arid regions.', tips:['Early sowing just before monsoon ensures good yield','Use downy mildew resistant varieties','Thinning at 15 days to one plant per hill','Roguing downy mildew affected plants immediately'], pests:['Shoot Fly','Stem Borer','Thrips'], diseases:['Downy Mildew','Ergot','Smut']},
  { id:'arhar',      name:'Arhar (Pigeonpea)', emoji:'🫘', season:'Kharif', duration:180, waterNeed:'Low', soilType:'All types',  yieldPerAcre:'6-10 qtl',  spacing:'75×20 cm', npk:{n:20,p:50,k:25},   description:'Important pulse crop for protein nutrition. Drought tolerant and soil improving.', tips:['Treat seeds with Rhizobium before sowing','Intercrop with short-duration crops','One irrigation at flowering is critical','Weed twice — at 30 and 60 days after sowing'], pests:['Pod Borer','Spotted Pod Borer','Blister Beetle'], diseases:['Fusarium Wilt','Sterility Mosaic','Phytophthora Blight']},
  { id:'moong',      name:'Moong (Green Gram)', emoji:'🫛', season:'Zaid/Kharif', duration:65, waterNeed:'Low', soilType:'Loamy Sandy', yieldPerAcre:'4-6 qtl', spacing:'30×10 cm', npk:{n:20,p:40,k:20}, description:'Short-duration pulse crop ideal for crop rotation. Improves soil nitrogen.', tips:['Use certified seeds inoculated with Rhizobium','Sow in zaid (March-April) for best results','Spray Mancozeb at first sign of leaf spot','Harvest when 70-80% pods turn black'], pests:['Whitefly','Aphid','Pod Borer'], diseases:['Yellow Mosaic Virus','Powdery Mildew','Cercospora Leaf Spot']},
  { id:'brinjal',    name:'Brinjal',     emoji:'🍆', season:'All year',duration:120, waterNeed:'Medium', soilType:'Loamy',       yieldPerAcre:'60-80 qtl',  spacing:'60×45 cm', npk:{n:100,p:60,k:60},  description:'Most commonly grown vegetable in India. Available in many local varieties.', tips:['Stake tall varieties','Monitor for shoot and fruit borer weekly','Remove and destroy affected shoots','Apply neem-based pesticide at first appearance of pest'], pests:['Shoot & Fruit Borer','Aphid','Jassid'], diseases:['Little Leaf','Phomopsis Blight','Damping Off']},
  { id:'okra',       name:'Okra (Bhindi)', emoji:'🌿', season:'Kharif/Zaid', duration:60, waterNeed:'Medium', soilType:'Loamy',  yieldPerAcre:'30-40 qtl',  spacing:'45×30 cm', npk:{n:60,p:40,k:50},   description:'Fast-growing vegetable with high market demand. Rich in fibre and vitamins.', tips:['Soak seeds overnight for better germination','Harvest every 2-3 days to maintain quality','Apply 10t FYM at land preparation','Do not over-water to prevent root diseases'], pests:['Jassid','Whitefly','Aphid'], diseases:['Yellow Vein Mosaic Virus','Powdery Mildew','Damping Off']},
  { id:'banana',     name:'Banana',      emoji:'🍌', season:'Annual',  duration:365, waterNeed:'High',   soilType:'Loamy',       yieldPerAcre:'200-250 qtl',spacing:'1.8×1.8 m', npk:{n:200,p:60,k:300}, description:'High-value perennial fruit crop with year-round income for farmers.', tips:['De-sucker regularly — keep only 1 ratoon','Cover bunches with blue polythene bags','Apply Gloeosporium lime paste on cuts','Harvest when top fingers of bunch turn yellow'], pests:['Banana Weevil','Nematode','Thrips'], diseases:['Panama Wilt','Sigatoka Leaf Spot','Bunchy Top Virus']},
  { id:'mango',      name:'Mango',       emoji:'🥭', season:'Perennial',duration:365,waterNeed:'Low',    soilType:'Loamy/Sandy', yieldPerAcre:'80-120 qtl', spacing:'10×10 m',  npk:{n:1000,p:500,k:1000},description:'King of fruits. Long-lived perennial with excellent export potential.', tips:['Apply paclobutrazol to regulate flowering','Intercrop in young orchards for income','Protect flowers from rain and frost','Apply copper fungicide post-harvest pruning'], pests:['Mango Hopper','Mealy Bug','Fruit Fly'], diseases:['Powdery Mildew','Anthracnose','Malformation']},
  { id:'papaya',     name:'Papaya',      emoji:'🍈', season:'Annual',  duration:240, waterNeed:'Medium', soilType:'Sandy Loam',  yieldPerAcre:'400-500 qtl',spacing:'1.8×1.8 m', npk:{n:200,p:200,k:250},description:'Fast-growing fruit crop with high nutritional value and year-round fruiting.', tips:['Plant 3 seeds per pit — keep 1 female/hermaphrodite','Avoid waterlogging — papaya is very sensitive','Apply micronutrients especially boron and zinc','Uproot and destroy virus-infected plants'], pests:['Mealybug','Fruit Fly','Mite'], diseases:['Papaya Ring Spot Virus','Anthracnose','Damping Off']},
  { id:'turmeric',   name:'Turmeric',    emoji:'🟡', season:'Kharif',  duration:270, waterNeed:'Medium', soilType:'Loamy/Red',   yieldPerAcre:'15-20 qtl', spacing:'45×20 cm', npk:{n:60,p:50,k:120},  description:'High-value spice crop with medicinal properties. India is world\'s largest producer.', tips:['Use disease-free mother rhizomes','Mulch with leaves or paddy straw','Earthing up at 60 and 120 days','Cure rhizomes properly for long storage'], pests:['Shoot Borer','Leaf Roller','Rhizome Scale'], diseases:['Rhizome Rot','Leaf Blotch','Leaf Spot']},
  { id:'ginger',     name:'Ginger',      emoji:'🫚', season:'Kharif',  duration:240, waterNeed:'High',   soilType:'Loamy/Red',   yieldPerAcre:'12-18 qtl', spacing:'25×20 cm', npk:{n:75,p:50,k:75},   description:'Important spice with high domestic and export demand. Prefers partial shade.', tips:['Treat rhizomes with Mancozeb before planting','Shade with coconut leaves in summer','Mulch thickly with crop residues','Harvest when leaves turn yellow'], pests:['Shoot Borer','Leaf Roller','Nematode'], diseases:['Soft Rot','Bacterial Wilt','Leaf Spot']},
  { id:'sunflower',  name:'Sunflower',   emoji:'🌻', season:'Rabi/Zaid',duration:90, waterNeed:'Medium', soilType:'Loamy',       yieldPerAcre:'6-8 qtl',   spacing:'60×30 cm', npk:{n:60,p:60,k:50},   description:'Short-duration oilseed crop with high oil content. Excellent for crop rotation.', tips:['Hive bees for pollination','Hand pollinate in small plots','Apply boron at bud stage','Harvest when back of head turns lemon yellow'], pests:['Capitulum Borer','Head Borer','Whitefly'], diseases:['Downy Mildew','Alternaria Blight','Sclerotinia Rot']},
  { id:'pomegranate',name:'Pomegranate', emoji:'💜', season:'Perennial',duration:365,waterNeed:'Low',    soilType:'Sandy Loam',  yieldPerAcre:'60-80 qtl', spacing:'5×4 m',    npk:{n:625,p:250,k:200},description:'Drought-tolerant fruit crop with high market value and medicinal properties.', tips:['Prune to open centre shape','Apply amrut jal bio-stimulant','Protect fruits from sunburn with paper bags','Harvest at correct maturity — 135-160 days after fruit set'], pests:['Anar Butterfly','Thrips','Mealybug'], diseases:['Bacterial Blight','Alternaria Fruit Spot','Cercospora Leaf Spot']}
];

const PESTS_DATA = [
  { id:'bhp', name:'Brown Planthopper', type:'pest', emoji:'🦗', affectedCrops:['Rice'], symptoms:['Yellowing in circular patches called hopper burn','Plants wilt suddenly as if burned','Whitish nymphs and adults visible at base of plants'], organicTreatment:['Spray neem oil 3% solution','Release mirid bug (Cyrtorhinus)','Drain field for 3-4 days'], chemicalTreatment:['Buprofezin 25% SC @ 400ml/acre','Imidacloprid 17.8% SL @ 100ml/acre','Dinotefuran 20% SG @ 80g/acre'], prevention:['Avoid excess nitrogen','Use resistant varieties like MTU-7029','Maintain field hygiene','Reduce plant density'], severity:'High'},
  { id:'yev', name:'Yellow Vein Mosaic Virus', type:'disease', emoji:'🦠', affectedCrops:['Okra','Moong'], symptoms:['Yellow veins forming network pattern on leaves','Reduced leaf size','Stunted growth and poor fruiting'], organicTreatment:['Remove and destroy infected plants','Spray neem oil to control vector whitefly','Use reflective mulch'], chemicalTreatment:['Imidacloprid for whitefly control','Thiamethoxam 25% WG @ 50g/acre','No direct cure — control vector'], prevention:['Use disease-resistant varieties','Plant early to avoid peak whitefly season','Remove weeds hosting whiteflies'], severity:'High'},
  { id:'lb', name:'Late Blight', type:'disease', emoji:'🍂', affectedCrops:['Potato','Tomato'], symptoms:['Water-soaked lesions on leaves','White fungal growth on undersurface','Brown sunken lesions on tubers'], organicTreatment:['Spray Bordeaux mixture (1%)','Remove infected leaves immediately','Improve air circulation by staking'], chemicalTreatment:['Mancozeb 75% WP @ 600g/acre','Metalaxyl 8% + Mancozeb 64% WP @ 400g/acre','Cymoxanil + Mancozeb @ 400g/acre'], prevention:['Plant certified seed','Avoid overhead irrigation','Destroy crop debris after harvest','Grow resistant varieties'], severity:'Very High'},
  { id:'fbw', name:'Fruit Borer', type:'pest', emoji:'🐛', affectedCrops:['Tomato','Brinjal','Chilli'], symptoms:['Pin-hole entry in fruits','Frass visible around entry hole','Fruits rot after borer entry'], organicTreatment:['Install pheromone traps @ 5/acre','Spray Beauveria bassiana 1%','Collect and destroy infested fruits'], chemicalTreatment:['Emamectin Benzoate 5% SG @ 80g/acre','Spinosad 45% SC @ 80ml/acre','Chlorantraniliprole 18.5% SC @ 60ml/acre'], prevention:['Grow Tagetes as trap crop','Regular harvesting reduces infestation','Avoid late planting'], severity:'High'},
  { id:'whitefly', name:'Whitefly', type:'pest', emoji:'🦟', affectedCrops:['Cotton','Tomato','Okra','Chilli'], symptoms:['Tiny white insects on leaf undersurface','Sticky honeydew on leaves','Sooty mold development','Yellow mosaic virus transmission'], organicTreatment:['Yellow sticky traps @ 10/acre','Neem oil 5% spray','Soap solution spray'], chemicalTreatment:['Thiamethoxam 25% WG @ 50g/acre','Spiromesifen 22.9% SC @ 200ml/acre','Acetamiprid 20% SP @ 100g/acre'], prevention:['Use reflective mulch','Plant basil as repellent','Avoid broadleaf weed hosts'], severity:'Medium'},
  { id:'pbw', name:'Pink Bollworm', type:'pest', emoji:'🐛', affectedCrops:['Cotton'], symptoms:['Rosette flowers (failed to open)','Dirty lock cotton with pink larvae inside','Seeds hollowed out'], organicTreatment:['Pheromone traps @ 5/acre from July','Trichogramma release @ 1,50,000/acre','Bt spray'], chemicalTreatment:['Chlorpyrifos 20% EC @ 1L/acre','Profenofos 50% EC @ 800ml/acre','Spinosad @ 100ml/acre'], prevention:['Use Bt cotton hybrids','Early sowing and early harvest','Stalk destruction after harvest'], severity:'Very High'},
  { id:'rust', name:'Yellow Rust (Wheat)', type:'disease', emoji:'🟡', affectedCrops:['Wheat'], symptoms:['Yellow-orange powdery pustules in stripes on leaves','Pustules arranged in dotted lines','Early infection causes heavy yield loss'], organicTreatment:['Grow resistant varieties','Balanced nutrition','Avoid excess nitrogen'], chemicalTreatment:['Propiconazole 25% EC @ 200ml/acre','Tebuconazole 25% EC @ 200ml/acre','Hexaconazole 5% EC @ 320ml/acre'], prevention:['Use rust-resistant varieties','Avoid late sowing','Destroy volunteer wheat plants'], severity:'High'},
  { id:'aphid', name:'Aphid', type:'pest', emoji:'🐜', affectedCrops:['Wheat','Mustard','Chilli','Cotton'], symptoms:['Colonies of small soft-bodied insects on tender parts','Sticky honeydew coating','Leaves curl and yellow'], organicTreatment:['Strong water spray to dislodge','Ladybird beetles (natural predator)','Neem seed kernel extract 5%'], chemicalTreatment:['Dimethoate 30% EC @ 300ml/acre','Imidacloprid 17.8% SL @ 60ml/acre','Thiamethoxam @ 40g/acre'], prevention:['Reflective silver mulch repels aphids','Intercrop with mustard as trap crop','Avoid excess nitrogenous fertilizer'], severity:'Medium'},
  { id:'fallawm', name:'Fall Army Worm', type:'pest', emoji:'🐛', affectedCrops:['Maize','Jowar'], symptoms:['Ragged leaf damage','Frass in leaf whorl','Pin-hole damage on fresh leaves','Larvae with inverted Y on head'], organicTreatment:['Emamectin benzoate (bio-rational)','Sand + ash in whorl','Trichogramma cards'], chemicalTreatment:['Chlorantraniliprole 18.5% SC @ 60ml/acre','Spinetoram 11.7% SC @ 100ml/acre','Thiamethoxam + Lambda-cyhalothrin @ 80ml/acre'], prevention:['Early sowing to avoid peak infestation','Pheromone traps monitoring','Deep ploughing to expose pupae'], severity:'Very High'},
  { id:'nematode', name:'Root-Knot Nematode', type:'pest', emoji:'🪱', affectedCrops:['Tomato','Banana','Ginger','Potato'], symptoms:['Galls/knots on roots','Stunted yellowing plants','Poor response to fertilizers'], organicTreatment:['Neem cake @ 250 kg/acre','Paecilomyces lilacinus application','Marigold intercrop/rotation'], chemicalTreatment:['Carbofuran 3G @ 8 kg/acre','Phorate 10G @ 4 kg/acre','Fluopyram seed treatment'], prevention:['Soil solarization for 45 days','Crop rotation with non-host crops','Use resistant rootstocks for grafting'], severity:'High'},
  { id:'thrips', name:'Thrips', type:'pest', emoji:'🦟', affectedCrops:['Onion','Chilli','Cotton','Okra'], symptoms:['Silver streaks on leaves','Curling and distortion of leaves and flowers','Tiny slender insects visible on flowers'], organicTreatment:['Blue sticky traps @ 8/acre','Spinosad (bio-based)','Neem oil spray'], chemicalTreatment:['Fipronil 5% SC @ 400ml/acre','Imidacloprid 17.8% SL @ 80ml/acre','Profenofos @ 500ml/acre'], prevention:['Reflective mulch repels thrips','Early sowing avoids peak season','Remove crop debris'], severity:'Medium'},
  { id:'weevil', name:'Banana Weevil Borer', type:'pest', emoji:'🪲', affectedCrops:['Banana'], symptoms:['Brown tunnels in corm','Plants snap at base in wind','Yellowing and wilting'], organicTreatment:['Chlorpyrifos-treated pseudostem trap','Metarhizium anisopliae application','Remove and destroy infected corms'], chemicalTreatment:['Chlorpyrifos 20% EC soil drenching','Carbofuran granules @ 20g/plant'], prevention:['Use weevil-free planting material','Trim and treat cut ends','Clean garden hygiene'], severity:'High'},
  { id:'blb', name:'Bacterial Leaf Blight (Rice)', type:'disease', emoji:'🟢', affectedCrops:['Rice'], symptoms:['Water-soaked lesions from leaf tips/margins','Yellowing and drying of leaves','Yellow ooze in morning on lesions'], organicTreatment:['Spray with Pseudomonas fluorescens','Avoid excess nitrogen','Field draining during severe attack'], chemicalTreatment:['Copper oxychloride 50% WP @ 600g/acre','Streptomycin sulphate + Copper oxychloride','Kasugamycin 3% SL'], prevention:['Use resistant varieties (IR-64, Swarna)','Avoid flooded conditions','Seed treatment with Pseudomonas'], severity:'High'},
  { id:'powdery', name:'Powdery Mildew', type:'disease', emoji:'⚪', affectedCrops:['Mango','Wheat','Okra','Moong'], symptoms:['White powdery coating on leaves, flowers, fruits','Leaf curl and flower drop in mango','Yield reduction'], organicTreatment:['Spray wettable sulphur 80% WP','Milk spray (1:9 dilution) weekly','Potassium bicarbonate spray'], chemicalTreatment:['Hexaconazole 5% EC @ 320ml/acre','Tebuconazole 25% EC @ 200ml/acre','Myclobutanil 10% WP @ 200g/acre'], prevention:['Avoid overcrowding — ensure air circulation','Remove infected plant parts','Spray during cool weather'], severity:'Medium'},
  { id:'fritfly', name:'Fruit Fly', type:'pest', emoji:'🪰', affectedCrops:['Mango','Guava','Papaya','Cucumber'], symptoms:['Puncture marks on fruits','Maggots inside pulp','Premature fruit drop'], organicTreatment:['Methyl eugenol traps @ 5/acre','Remove and destroy fallen fruits daily','Protein hydrolysate bait spray'], chemicalTreatment:['Malathion 50% EC bait spray','Fenthion 100% EC @ 1ml/L in bait','Deltamethrin in bait spray'], prevention:['Harvest at correct maturity','Bag fruits in paper bags','Soil ploughing to expose pupae'], severity:'High'},
  { id:'pmbollworm', name:'American Bollworm', type:'pest', emoji:'🐛', affectedCrops:['Cotton','Tomato'], symptoms:['Bored bolls/fruits with round hole','Caterpillar feeding on flowers and bolls','Heavy yield loss in 2nd and 3rd generation'], organicTreatment:['NPV (Nuclear Polyhedrosis Virus) spray','Trichogramma chilonis release','Pheromone traps'], chemicalTreatment:['Chlorantraniliprole 18.5% SC @ 60ml/acre','Spinosad 45% SC @ 80ml/acre','Emamectin benzoate @ 80g/acre'], prevention:['Intercrop with cowpea to attract and kill','Grow sunflower as trap crop','Avoid late sowing'], severity:'Very High'},
  { id:'smut', name:'Smut (Sugarcane/Maize)', type:'disease', emoji:'⚫', affectedCrops:['Sugarcane','Maize','Jowar'], symptoms:['Long black whip emerging from shoot in sugarcane','Black powdery spores in ear in maize','Stunted growth'], organicTreatment:['Rogue out and destroy whips immediately','Use resistant varieties','Hot water treatment of seed material'], chemicalTreatment:['Carboxin 37.5% + Thiram 37.5% DS seed treatment','Mancozeb spray on young crop'], prevention:['Use certified smut-free planting material','Crop rotation','Avoid ratooning from infected crop'], severity:'Medium'},
  { id:'wilt', name:'Fusarium Wilt', type:'disease', emoji:'🥀', affectedCrops:['Cotton','Arhar','Tomato','Banana'], symptoms:['Sudden wilting without yellowing','Brown vascular discolouration in stem','Death of entire plant or branches'], organicTreatment:['Trichoderma viride @ 4 kg/acre mixed in FYM','Pseudomonas fluorescens soil drench','Organic matter addition improves suppressiveness'], chemicalTreatment:['Carbendazim 50% WP @ 500g/acre soil drench','Propiconazole 25% EC stem injection in banana'], prevention:['Soil solarization before planting','Avoid monoculture — crop rotation','Use resistant/tolerant varieties'], severity:'Very High'},
  { id:'anthr', name:'Anthracnose', type:'disease', emoji:'🔴', affectedCrops:['Mango','Chilli','Soybean','Papaya'], symptoms:['Dark brown-black sunken lesions on fruits','Irregular dead spots on leaves','Post-harvest fruit rotting in mango'], organicTreatment:['Spray Bordeaux mixture 1%','Neem oil + soap solution','Copper-based organic sprays'], chemicalTreatment:['Carbendazim 50% WP @ 500g/acre','Mancozeb + Carbendazim combination','Azoxystrobin 23% SC @ 200ml/acre'], prevention:['Good orchard sanitation','Avoid overhead irrigation','Pre-harvest spray with copper fungicide'], severity:'High'},
  { id:'leafminer', name:'Leaf Miner', type:'pest', emoji:'🦟', affectedCrops:['Groundnut','Tomato','Potato'], symptoms:['Zigzag mines/tunnels visible inside leaf','Brown papery patches','Reduced photosynthesis'], organicTreatment:['Remove heavily mined leaves','Yellow sticky traps','Neem-based spray'], chemicalTreatment:['Imidacloprid 17.8% SL @ 60ml/acre','Cyromazine 75% WP @ 100g/acre','Abamectin 1.8% EC @ 200ml/acre'], prevention:['Monitor regularly from seedling stage','Destroy crop debris','Avoid excessive nitrogen'], severity:'Low'}
];

const SCHEMES_DATA = [
  { id:'pmkisan', name:'PM-KISAN', fullName:'Pradhan Mantri Kisan Samman Nidhi', ministry:'Ministry of Agriculture', category:'Subsidy', benefit:'₹6,000/year (₹2,000 in 3 installments)', eligibility:['Small/marginal farmer','Land holding ≤ 2 hectares','Valid Aadhaar','Linked bank account','Not a government employee/taxpayer'], applicationProcess:['Visit nearest CSC or Agriculture Department','Fill PM-KISAN registration form','Submit Aadhaar, land documents, bank passbook','District Agriculture Officer verifies','Registered on PM-KISAN portal','Amount transferred directly to bank'], deadline:'Rolling', link:'https://pmkisan.gov.in', amount:6000, description:'Direct income support scheme providing financial assistance to farmer families.'},
  { id:'pmfby', name:'PMFBY', fullName:'Pradhan Mantri Fasal Bima Yojana', ministry:'Ministry of Agriculture', category:'Insurance', benefit:'Full coverage against crop loss due to natural calamities', eligibility:['All farmers growing notified crops','Both loanee and non-loanee farmers','Aadhaar mandatory'], applicationProcess:['Enroll before cutoff date (varies by season)','Apply through bank/CSC/insurance company portal','Pay premium: 2% for Kharif, 1.5% for Rabi, 5% for commercial crops','Submit land and sowing details','Claim filed within 72 hours of damage'], deadline:'Before season sowing cutoff', link:'https://pmfby.gov.in', amount:0, description:'Comprehensive crop insurance at very low premium rates. Government pays the rest.'},
  { id:'kcc', name:'KCC', fullName:'Kisan Credit Card', ministry:'Ministry of Finance / NABARD', category:'Credit', benefit:'Short-term credit at 4% interest rate (with 3% government subvention)', eligibility:['All individual/joint farmers','Tenant farmers, sharecroppers','SHG/JLG members','Minimum agricultural land'], applicationProcess:['Visit nearest bank (SBI, PNB, cooperative bank)','Submit KCC application with land documents','Bank assesses credit limit based on landholding','Card issued within 14 days','Use for seeds, fertilizers, pesticides, equipment'], deadline:'Rolling', link:'https://agricoop.gov.in', amount:300000, description:'Single credit facility for all agricultural needs at subsidized interest rates.'},
  { id:'pmkusum', name:'PM-KUSUM', fullName:'Pradhan Mantri Kisan Urja Suraksha evem Uttham Mahabhiyan', ministry:'Ministry of New and Renewable Energy', category:'Technology', benefit:'60% subsidy on solar pumps (30% central + 30% state)', eligibility:['Individual farmers','Farmer groups/cooperatives','Panchayats','Water User Associations'], applicationProcess:['Apply on state DISCOM/RREC portal','Submit land, ID documents','Component-B: 7.5 HP solar pump with 60% subsidy','Pay only 40% cost (or avail loan for that)','Installation within 90 days'], deadline:'State-wise rolling', link:'https://mnre.gov.in', amount:0, description:'Provides solar pumps and solar energy to farmers to reduce electricity costs.'},
  { id:'pkvy', name:'PKVY', fullName:'Paramparagat Krishi Vikas Yojana', ministry:'Ministry of Agriculture', category:'Subsidy', benefit:'₹50,000/ha for 3 years for certified organic farming', eligibility:['Farmers willing to adopt organic farming','Form cluster of 20 hectares minimum','Willing to undergo organic certification'], applicationProcess:['Form farmers cluster of 20+ hectares','Apply through State Agriculture Department','Get PGS certification process started','Maintain detailed records','Receive financial assistance in installments'], deadline:'State-wise', link:'https://agricoop.gov.in', amount:50000, description:'Promotes organic farming with financial support and market linkage assistance.'},
  { id:'rkvy', name:'RKVY-RAFTAAR', fullName:'Rashtriya Krishi Vikas Yojana - Remunerative Approaches', ministry:'Ministry of Agriculture', category:'Infrastructure', benefit:'Grants for farm infrastructure, agri-business projects', eligibility:['Individual farmers','FPOs (Farmer Producer Organisations)','Agri-startups','State Agriculture Departments'], applicationProcess:['Apply through RKVY State-level nodal agency','Submit project proposal with DPR','State Level Sanctioning Committee approves','Funds released in tranches','Completion report required'], deadline:'Annual application cycle', link:'https://rkvy.nic.in', amount:0, description:'Infrastructure development and modernization of agriculture with state-level flexibility.'},
  { id:'midh', name:'MIDH', fullName:'Mission for Integrated Development of Horticulture', ministry:'Ministry of Agriculture', category:'Subsidy', benefit:'25-50% subsidy on horticulture infrastructure, planting material', eligibility:['Farmers growing fruits/vegetables/flowers','FPOs and cooperatives','Individual farmers with land records'], applicationProcess:['Apply through State Horticulture Mission','Submit application with land documents','Subsidy on approved components (drip, nursery, poly house, etc.)','Site inspection by department officer','Subsidy released to bank account'], deadline:'State-wise (April-September window)', link:'https://midh.gov.in', amount:0, description:'Comprehensive scheme for development of horticulture sector with multiple components.'},
  { id:'enam', name:'eNAM', fullName:'National Agriculture Market (e-NAM)', ministry:'Ministry of Agriculture', category:'Market', benefit:'Transparent online trading at better prices, no middlemen', eligibility:['All farmers with Aadhaar','Must be registered on eNAM platform','Land near eNAM-connected mandi'], applicationProcess:['Register at eNAM.gov.in or nearest mandi','Submit Aadhaar, bank account, mobile number','Bring produce to APMC mandi','Electronic weighment and testing','Online bidding — best price credited to bank'], deadline:'Rolling registration', link:'https://enam.gov.in', amount:0, description:'Online trading platform connecting farmers directly with buyers across India.'},
  { id:'shc', name:'SHC Scheme', fullName:'Soil Health Card Scheme', ministry:'Ministry of Agriculture', category:'Input', benefit:'Free soil testing every 2 years, fertilizer recommendations', eligibility:['All farmers who apply','No restriction on land holding'], applicationProcess:['Collect soil sample as per guide (zig-zag sampling)','Submit at nearest soil testing lab or KVK','Test conducted for 12 parameters','Card issued with fertilizer recommendations','Apply as per card recommendations'], deadline:'Rolling (apply any time)', link:'https://soilhealth.dac.gov.in', amount:0, description:'Free soil testing and customized fertilizer recommendation cards for every farm.'},
  { id:'nmsa', name:'NMSA', fullName:'National Mission for Sustainable Agriculture', ministry:'Ministry of Agriculture', category:'Subsidy', benefit:'Subsidies for water conservation, organic farming, soil health', eligibility:['Farmers in rainfed areas','Willing to adopt conservation practices','Apply through state agriculture dept'], applicationProcess:['Submit application through District Agriculture Office','Components: drip/sprinkler subsidy, SHC, organic manure','Site inspection and approval','Infrastructure created and certified','Subsidy released to beneficiary account'], deadline:'Annual (Oct-March)', link:'https://nmsa.dac.gov.in', amount:0, description:'Promotes sustainable agriculture practices with focus on rainfed and water-stressed areas.'},
  { id:'pmmsy', name:'PMMSY', fullName:'PM Matsya Sampada Yojana', ministry:'Ministry of Fisheries', category:'Subsidy', benefit:'40-60% subsidy on fisheries infrastructure (fish farmers also eligible)', eligibility:['Fishermen/fish farmers','Aquaculture farmers','SC/ST farmers get additional 10%'], applicationProcess:['Apply through State Fisheries Department','Submit project proposal','Activity-specific subsidy approved','Implementation with 2-year monitoring'], deadline:'State-wise', link:'https://pmmsy.dac.gov.in', amount:0, description:'Comprehensive scheme for sustainable and responsible development of fisheries sector.'},
  { id:'nabkisan', name:'NABARD Kisan', fullName:'NABARD Kisan Credit and Rural Infrastructure', ministry:'NABARD', category:'Credit', benefit:'Agricultural term loans at 7-9% interest with government subvention', eligibility:['All farmers','SHGs and farmer cooperatives','Agri allied activities'], applicationProcess:['Apply through NABARD-linked rural banks','Submit land documents and project report','Loan sanctioned within 30 days','For term loans: collateral may be required','Repayment in 3-7 years'], deadline:'Rolling', link:'https://nabard.org', amount:0, description:'NABARD provides refinance support for agricultural credit through banks and cooperatives.'},
  { id:'agriinfra', name:'AIFF', fullName:'Agriculture Infrastructure Fund', ministry:'Ministry of Agriculture', category:'Infrastructure', benefit:'₹1-2 crore loan with 3% interest subvention for 7 years', eligibility:['Farmers and FPOs','Agri-entrepreneurs','SHGs and cooperatives','State agencies'], applicationProcess:['Apply on agriinfra.dac.gov.in','Submit business plan and DPR','Bank appraisal and loan sanction','Create warehouse, cold chain, collection center etc.','Interest subvention applied automatically'], deadline:'Rolling till March 2033', link:'https://agriinfra.dac.gov.in', amount:2000000, description:'Long-term financing for post-harvest management infrastructure.'},
  { id:'wdra', name:'WDRA Pledge Finance', fullName:'Warehouse Development and Regulatory Authority', ministry:'Ministry of Consumer Affairs', category:'Credit', benefit:'70-80% loan against warehouse receipt of stored produce', eligibility:['Farmers with produce in WDRA-registered warehouses','All crops covered'], applicationProcess:['Store produce in WDRA warehouse','Get electronic negotiable warehouse receipt (eNWR)','Pledge receipt at bank for loan','Sell produce when prices are favourable','Repay loan and retrieve produce'], deadline:'Rolling', link:'https://wdra.gov.in', amount:0, description:'Enables farmers to get credit against stored produce and sell when prices are better.'},
  { id:'dbt', name:'DBT Fertilizer Subsidy', fullName:'Direct Benefit Transfer for Fertilizers', ministry:'Ministry of Chemicals', category:'Subsidy', benefit:'Subsidized fertilizers (Urea at ₹266/bag, DAP at ₹1,350/bag)', eligibility:['All farmers with Aadhaar','Purchase through PoS machine at retailer'], applicationProcess:['Visit nearest authorized fertilizer retailer','Give Aadhaar for biometric authentication','Buy subsidized fertilizers at maximum retail price','No separate registration needed','Subsidy goes to manufacturer, not farmer directly'], deadline:'Rolling', link:'https://dbtbharat.gov.in', amount:0, description:'Fertilizer subsidy through direct sale at subsidized rates via Aadhaar-authenticated PoS.'}
];

const EQUIPMENT_DATA = [
  { id:'tractor', name:'Tractor', emoji:'🚜', category:'Tillage', description:'Primary power source for all farm operations. Available in 35-90 HP range.', uses:['Ploughing and tillage','Sowing and planting','Transport of produce','Running irrigation pumps'], rentalCost:'₹800-1,200/hour', purchaseCost:'₹5-15 Lakhs', maintenanceTips:['Change engine oil every 200 hours','Check air filter daily','Grease all lubrication points weekly','Flush radiator coolant annually'], specs:{power:'35-90 HP', fuelType:'Diesel', avgFuelConsumption:'4-8 L/hour'}},
  { id:'rotavator', name:'Rotavator', emoji:'⚙️', category:'Tillage', description:'Tractor-mounted implement for fine seedbed preparation. Replaces 2-3 ploughings.', uses:['Primary and secondary tillage','Incorporation of crop residue','Seedbed preparation for vegetables'], rentalCost:'₹500-700/hour', purchaseCost:'₹60,000-1,20,000', maintenanceTips:['Sharpen blades every 50 hours','Check bolt tightness before use','Oil gearbox monthly'], specs:{width:'1.2-2.4 m', blades:'24-48', depth:'12-18 cm'}},
  { id:'seedDrill', name:'Seed Drill', emoji:'🌾', category:'Sowing', description:'Ensures precise seed placement at correct depth and spacing. Saves 20-30% seed.', uses:['Row sowing of wheat, maize, pulses','Fertigation while sowing','Conservation agriculture sowing'], rentalCost:'₹400-600/hour', purchaseCost:'₹30,000-80,000', maintenanceTips:['Clean tubes after each use','Check seed metering plates for wear','Lubricate all moving parts'], specs:{rows:'7-11', spacing:'20-22.5 cm adjustable', acreagePerDay:'4-6 acres'}},
  { id:'sprayer', name:'Power Sprayer', emoji:'💦', category:'Protection', description:'Engine-powered sprayer for efficient pesticide/fertilizer application.', uses:['Pesticide application','Foliar fertilizer spraying','Weedicide application','Fungicide spraying'], rentalCost:'₹200-400/hour', purchaseCost:'₹8,000-25,000', maintenanceTips:['Clean tank and nozzles after every use','Check nozzle uniformity regularly','Replace rubber seals annually'], specs:{capacity:'16-35 L', motorPower:'1.5-3 HP', coverage:'1-2 acres/hour'}},
  { id:'dripSystem', name:'Drip Irrigation System', emoji:'💧', category:'Irrigation', description:'Most efficient irrigation method. Delivers water directly to root zone.', uses:['Vegetables and fruit crops','Row crops','Horticultural crops','Water-scarce areas'], rentalCost:'N/A (purchased)', purchaseCost:'₹35,000-60,000/acre', maintenanceTips:['Flush laterals monthly','Check drippers for clogging weekly','Use sand filter and screen filter','Acid treatment for carbonate deposits'], specs:{efficiency:'90-95%', waterSaving:'40-60% vs flood', pressureRequired:'1.5-2.5 kg/cm²'}},
  { id:'sprinkler', name:'Sprinkler System', emoji:'🌊', category:'Irrigation', description:'Overhead irrigation system suitable for most crops and terrains.', uses:['Wheat, groundnut, vegetables','Lawns and nurseries','Germination irrigation','Frost protection'], rentalCost:'₹150-250/hour', purchaseCost:'₹15,000-30,000/acre', maintenanceTips:['Clean nozzles monthly','Check for uniform coverage','Operate during low-wind periods','Winterize pipes in cold areas'], specs:{efficiency:'70-80%', waterSaving:'20-30% vs flood', coverage:'10-18 m radius per sprinkler'}},
  { id:'harvester', name:'Combine Harvester', emoji:'🌾', category:'Harvesting', description:'Mechanically harvests, threshes, and cleans grain in one operation.', uses:['Wheat, rice, soybean harvesting','Reduces harvest losses','Timely harvesting','Reduces labour cost 80%'], rentalCost:'₹1,500-2,500/acre', purchaseCost:'₹15-30 Lakhs', maintenanceTips:['Service before season begins','Check cutting blade sharpness','Adjust concave clearance per crop','Clean grain tank and auger after each day'], specs:{capacity:'3-5 acres/hour', grainLoss:'< 1%', fuelConsumption:'8-12 L/acre'}},
  { id:'weeder', name:'Power Weeder', emoji:'🌱', category:'Tillage', description:'Motorized inter-row weeding machine. Replaces manual weeding labour.', uses:['Inter-row weeding in vegetables','Maize, sugarcane weeding','Soil aeration','Light soil tillage'], rentalCost:'₹300-500/day', purchaseCost:'₹25,000-80,000', maintenanceTips:['Clean blade area after use','Check chain/belt tension weekly','Change gearbox oil every 100 hours'], specs:{rowSpacing:'25-75 cm adjustable', enginePower:'2-7 HP', coverage:'0.5-1 acre/day'}},
  { id:'transplanter', name:'Paddy Transplanter', emoji:'🌿', category:'Sowing', description:'Mechanically transplants paddy seedlings. Reduces labour cost by 70%.', uses:['Paddy transplanting','Vegetable seedling transplanting','Uniform spacing for better yield'], rentalCost:'₹2,000-3,000/acre', purchaseCost:'₹3-8 Lakhs (ride-on)', maintenanceTips:['Clean fingers and arms daily','Lubricate all pivot points','Check mat feeder mechanism','Store dry after season'], specs:{rows:'4-8 rows', spacing:'30×14 cm (adjustable)', capacity:'0.5-1 acre/hour'}},
  { id:'pump', name:'Submersible Pump', emoji:'⚡', category:'Irrigation', description:'Electric/diesel pump for lifting groundwater for irrigation.', uses:['Borewell irrigation','Canal water lifting','Pond pumping','Drainage'], rentalCost:'₹100-200/hour', purchaseCost:'₹8,000-30,000', maintenanceTips:['Check motor insulation annually','Maintain water level above pump','Use voltage stabilizer','Service impeller every 2 years'], specs:{discharge:'50-500 LPM', head:'20-100 m', power:'1-10 HP'}},
  { id:'tarpaulin', name:'Tarpaulin (Threshing)', emoji:'🟦', category:'Post-harvest', description:'Essential for grain threshing, drying and storage on farm.', uses:['Grain threshing floor','Sun drying of grains','Temporary grain storage','Protecting produce from rain'], rentalCost:'₹50-100/day', purchaseCost:'₹500-2,000', maintenanceTips:['Clean and dry before storage','Repair holes with repair kit','Fold and store away from sunlight'], specs:{sizes:'6×4m to 12×8m', material:'HDPE woven', GSM:'90-200'}},
  { id:'thresher', name:'Thresher', emoji:'⚙️', category:'Post-harvest', description:'Mechanically separates grain from stalks. Much faster than manual threshing.', uses:['Wheat, paddy, soybean, maize threshing','Reduces grain loss','Faster processing'], rentalCost:'₹500-800/hour', purchaseCost:'₹50,000-2,00,000', maintenanceTips:['Check and tighten belts before use','Clean feed drum and sieves daily','Lubricate bearings every 8 hours','Store covered in dry place'], specs:{capacity:'300-1000 kg/hour', requiredPower:'5-15 HP', grainLoss:'< 2%'}},
  { id:'soilTester', name:'Soil Testing Kit', emoji:'🧪', category:'Diagnostic', description:'Field soil testing kit for quick pH, NPK, and moisture measurement.', uses:['Field soil pH testing','NPK quick estimate','Moisture content check','EC (salinity) measurement'], rentalCost:'N/A', purchaseCost:'₹1,500-8,000', maintenanceTips:['Replace chemicals as per expiry','Keep in cool dry place','Calibrate with buffer solutions','Keep meter probe clean'], specs:{parameters:'pH, N, P, K, EC, Moisture', accuracy:'±0.1 pH', batteryLife:'500+ tests'}},
  { id:'drone', name:'Agricultural Drone', emoji:'🚁', category:'Technology', description:'Unmanned aerial vehicle for spraying, monitoring and surveying.', uses:['Precision pesticide spraying','Crop monitoring and scouting','NDVI crop health mapping','Seed sowing in inaccessible areas'], rentalCost:'₹400-600/acre', purchaseCost:'₹5-12 Lakhs', maintenanceTips:['Check propellers before each flight','Keep batteries charged 50% for storage','Update firmware regularly','Inspect motors and ESCs monthly'], specs:{capacity:'10-16 L tank', coverage:'1 acre per 10 minutes', battery:'25-30 min flight time'}},
  { id:'coldStorage', name:'Cold Storage Unit', emoji:'❄️', category:'Post-harvest', description:'On-farm cold storage for extending shelf life of perishable produce.', uses:['Vegetable and fruit storage','Seed storage','Flower storage','Extending marketing window'], rentalCost:'₹2-5/kg/month (commercial)', purchaseCost:'₹5-25 Lakhs (10-50 MT)', maintenanceTips:['Check insulation for cracks annually','Service compressor before season','Maintain temperature logs','Ensure backup power source'], specs:{tempRange:'0-20°C', humidity:'85-95% RH', capacity:'10-100 MT'}}
];

const TECH_DATA = [
  { id:'drone_farming', name:'Drone-based Crop Spraying', emoji:'🚁', category:'AI', description:'Drones spray precise quantities of pesticides/fertilizers, reducing chemical use by 30% and labour costs dramatically.', benefits:['30% reduction in pesticide use','10x faster than manual spraying','Reaches inaccessible areas','Real-time crop health mapping'], cost:'₹400-600/acre rental', implementation:'Hire from local drone service providers, IARI-empanelled operators or agri-drone startups.', yieldIncrease:10, waterSaving:0, labourSaving:80, roiYears:0},
  { id:'iot_sensors', name:'IoT Soil & Crop Sensors', emoji:'📡', category:'IoT', description:'Wireless sensors in field measure soil moisture, temperature, pH and crop conditions in real-time, sending data to your smartphone.', benefits:['Precise irrigation scheduling','Early stress detection','Remote farm monitoring','Data-driven decisions'], cost:'₹15,000-50,000 for sensor network', implementation:'Install sensors at 3-5 locations per field, connect to cloud via GSM, monitor on app.', yieldIncrease:15, waterSaving:30, labourSaving:40, roiYears:3},
  { id:'precision_agri', name:'Precision Agriculture (GPS)', emoji:'🛰️', category:'Digital', description:'GPS-guided tractors, variable rate application of seeds and fertilizers based on soil variability maps.', benefits:['Reduce input costs 15-20%','Uniform crop stand','Soil variability management','Automated tractor operations'], cost:'₹2-5 Lakhs for GPS system', implementation:'Purchase GPS receiver compatible with tractor, create prescription maps with agronomist help.', yieldIncrease:12, waterSaving:10, labourSaving:25, roiYears:4},
  { id:'ai_monitoring', name:'AI Crop Disease Detection', emoji:'🤖', category:'AI', description:'Smartphone apps using AI can identify crop diseases and pests from photos within seconds, suggesting treatments.', benefits:['Instant disease identification','Treatment recommendations','No expert required in field','Prevents crop losses'], cost:'Free to ₹2,000/year subscription', implementation:'Download apps like Plantix, AgriApp, Kisan AI. Take photo of affected leaf and get diagnosis.', yieldIncrease:8, waterSaving:0, labourSaving:15, roiYears:1},
  { id:'drip_smart', name:'Smart Drip Irrigation', emoji:'💧', category:'IoT', description:'Automated drip irrigation controlled by soil moisture sensors and weather data. Irrigates only when crops need water.', benefits:['40-60% water saving','Reduced fertilizer loss','Better crop quality','Automation of irrigation'], cost:'₹40,000-70,000/acre', implementation:'Install drip system with soil sensors and controller, connect to smartphone, set thresholds.', yieldIncrease:20, waterSaving:50, labourSaving:60, roiYears:4},
  { id:'hydroponics', name:'Hydroponics', emoji:'🌿', category:'Biological', description:'Growing crops without soil using nutrient-rich water. Up to 10x more yield per unit area.', benefits:['10x yield per unit area','90% water saving','Year-round production','No soil-borne diseases'], cost:'₹50-200/sq ft setup', implementation:'Start with NFT or DWC system for lettuce/herbs. Join training program from IARI or state horticulture dept.', yieldIncrease:400, waterSaving:90, labourSaving:0, roiYears:3},
  { id:'vertical_farming', name:'Vertical Farming', emoji:'🏗️', category:'Biological', description:'Multi-layer indoor farming with LED lighting. Maximum yield from minimum land.', benefits:['20-30 crop cycles per year','Independent of weather','Urban farming possibility','Minimum land use'], cost:'₹10,000-50,000/sq ft', implementation:'Start with leafy greens, herbs. Pilot with 200 sq ft unit. Sell to hotels, restaurants for premium price.', yieldIncrease:1000, waterSaving:95, labourSaving:0, roiYears:5},
  { id:'solar_pump', name:'Solar Irrigation Pumps', emoji:'☀️', category:'Mechanical', description:'Solar-powered water pumps eliminate electricity bills and enable irrigation in off-grid areas.', benefits:['Zero electricity cost','25-year system life','Government 60% subsidy','Works in remote areas'], cost:'₹2-4 Lakhs (before 60% subsidy)', implementation:'Apply under PM-KUSUM scheme for 60% subsidy. Purchase from MNRE-approved manufacturer.', yieldIncrease:0, waterSaving:0, labourSaving:30, roiYears:5},
  { id:'poly_house', name:'Polyhouse/Greenhouse Farming', emoji:'🏡', category:'Mechanical', description:'Controlled environment agriculture for high-value vegetables and flowers with premium market access.', benefits:['3-4 crop cycles/year','Protection from weather extremes','50% subsidy under MIDH','Premium price realization'], cost:'₹600-1,200/sq m (50% subsidy available)', implementation:'Apply for MIDH subsidy from state horticulture dept. Build polyhouse, grow capsicum, cucumber, gerbera.', yieldIncrease:200, waterSaving:40, labourSaving:0, roiYears:4},
  { id:'blockchain', name:'Blockchain Traceability', emoji:'🔗', category:'Digital', description:'QR code-based traceability from farm to consumer. Fetch premium prices and access export markets.', benefits:['Premium price for traceable produce','Access to export markets','Consumer trust and loyalty','FPO empowerment'], cost:'₹5,000-20,000/year platform subscription', implementation:'Join FPO with blockchain platform, register farm, tag produce, sell to traceable supply chain buyers.', yieldIncrease:0, waterSaving:0, labourSaving:0, roiYears:2}
];

const FERTILIZER_RECO = {
  rice:     {basal:[{name:'Urea',qty:'27 kg',when:'Before transplanting'},{name:'DAP',qty:'50 kg',when:'Basal'},{name:'MOP',qty:'33 kg',when:'Basal'}], top:[{name:'Urea',qty:'27 kg',when:'25 days after transplanting'},{name:'Urea',qty:'27 kg',when:'45 days after transplanting'}]},
  wheat:    {basal:[{name:'Urea',qty:'27 kg',when:'Sowing time'},{name:'DAP',qty:'50 kg',when:'Basal'},{name:'MOP',qty:'27 kg',when:'Basal'}], top:[{name:'Urea',qty:'54 kg',when:'First irrigation (CRI stage)'}]},
  maize:    {basal:[{name:'Urea',qty:'33 kg',when:'Sowing'},{name:'DAP',qty:'65 kg',when:'Basal'},{name:'MOP',qty:'33 kg',when:'Basal'}], top:[{name:'Urea',qty:'33 kg',when:'30 days'},{name:'Urea',qty:'44 kg',when:'50 days'}]},
  tomato:   {basal:[{name:'FYM/Compost',qty:'4 tonnes',when:'Land preparation'},{name:'DAP',qty:'50 kg',when:'Basal'},{name:'MOP',qty:'50 kg',when:'Basal'}], top:[{name:'Urea',qty:'20 kg',when:'30 days'},{name:'Urea',qty:'20 kg',when:'60 days'},{name:'Urea',qty:'20 kg',when:'Fruiting'}]},
  potato:   {basal:[{name:'Urea',qty:'40 kg',when:'At planting'},{name:'DAP',qty:'100 kg',when:'Basal'},{name:'MOP',qty:'100 kg',when:'Basal'}], top:[{name:'Urea',qty:'40 kg',when:'Earthing up (25-30 days)'}]},
  cotton:   {basal:[{name:'DAP',qty:'50 kg',when:'Sowing'},{name:'MOP',qty:'33 kg',when:'Basal'},{name:'FYM',qty:'5 tonnes',when:'Land prep'}], top:[{name:'Urea',qty:'44 kg',when:'30 days'},{name:'Urea',qty:'44 kg',when:'Squaring stage'}]},
  onion:    {basal:[{name:'FYM',qty:'10 tonnes',when:'Bed preparation'},{name:'DAP',qty:'50 kg',when:'Basal'},{name:'MOP',qty:'33 kg',when:'Basal'}], top:[{name:'Urea',qty:'25 kg',when:'30 days'},{name:'Urea',qty:'25 kg',when:'Bulbing stage'}]},
  default:  {basal:[{name:'FYM/Compost',qty:'5 tonnes',when:'Land preparation'},{name:'DAP',qty:'50 kg',when:'Basal at sowing'},{name:'MOP',qty:'33 kg',when:'Basal'}], top:[{name:'Urea',qty:'27 kg',when:'30 days after sowing'},{name:'Urea',qty:'27 kg',when:'60 days after sowing'}]}
};

const BASE_MARKET_PRICES = [
  {crop:'Rice',        emoji:'🌾', price:2183, unit:'Rs/quintal', change:1.2,  market:'Delhi (Azadpur)'},
  {crop:'Wheat',       emoji:'🌻', price:2275, unit:'Rs/quintal', change:-0.5, market:'Amritsar'},
  {crop:'Maize',       emoji:'🌽', price:1850, unit:'Rs/quintal', change:2.1,  market:'Nizamabad'},
  {crop:'Onion',       emoji:'🧅', price:1800, unit:'Rs/quintal', change:-3.2, market:'Lasalgaon'},
  {crop:'Tomato',      emoji:'🍅', price:3200, unit:'Rs/quintal', change:8.5,  market:'Kolar'},
  {crop:'Potato',      emoji:'🥔', price:1100, unit:'Rs/quintal', change:-1.1, market:'Agra'},
  {crop:'Cotton',      emoji:'🌿', price:6500, unit:'Rs/quintal', change:0.8,  market:'Rajkot'},
  {crop:'Soybean',     emoji:'🫘', price:4350, unit:'Rs/quintal', change:1.5,  market:'Indore'},
  {crop:'Groundnut',   emoji:'🥜', price:5800, unit:'Rs/quintal', change:2.3,  market:'Junagadh'},
  {crop:'Sugarcane',   emoji:'🎋', price:350,  unit:'Rs/quintal', change:0.0,  market:'UP (SAP)'},
  {crop:'Chilli',      emoji:'🌶️', price:12000,unit:'Rs/quintal', change:5.2,  market:'Guntur'},
  {crop:'Turmeric',    emoji:'🟡', price:8200, unit:'Rs/quintal', change:-2.1, market:'Nizamabad'},
  {crop:'Mustard',     emoji:'🌼', price:5800, unit:'Rs/quintal', change:0.9,  market:'Jaipur'},
  {crop:'Arhar',       emoji:'🫘', price:6950, unit:'Rs/quintal', change:1.8,  market:'Gulbarga'},
  {crop:'Moong',       emoji:'🫛', price:7800, unit:'Rs/quintal', change:-0.7, market:'Jalgaon'},
  {crop:'Ginger',      emoji:'🫚', price:6500, unit:'Rs/quintal', change:3.4,  market:'Cochin'},
  {crop:'Banana',      emoji:'🍌', price:2200, unit:'Rs/quintal', change:1.0,  market:'Anantapur'},
  {crop:'Pomegranate', emoji:'💜', price:8000, unit:'Rs/quintal', change:4.2,  market:'Solapur'},
  {crop:'Jowar',       emoji:'🌾', price:2500, unit:'Rs/quintal', change:0.5,  market:'Latur'},
  {crop:'Bajra',       emoji:'🌾', price:2350, unit:'Rs/quintal', change:1.1,  market:'Barmer'}
];

const FAQ_DATA = [
  {q:'How do I register on SmartFarm?', a:'Click "Register here" on the login screen, fill in your details including name, phone, location, farm size and crop type. Your account will be created instantly and stored securely on your device.'},
  {q:'Is my farm data safe and private?', a:'Yes. All your data is stored locally on your device (localStorage). No data is sent to any server. Only weather data uses an external API (Open-Meteo) which is completely anonymous.'},
  {q:'How do I get weather information for my location?', a:'Go to Weather Monitoring page and allow location access. The app uses your GPS coordinates to fetch real-time weather from the Open-Meteo free API. Alternatively, you can enter your district manually.'},
  {q:'Can I use SmartFarm offline?', a:'Most features work offline since all data is stored locally. Only the Weather page requires internet to fetch live forecasts. Crop, expense, and farm management work completely offline.'},
  {q:'How do I apply for PM-KISAN scheme?', a:'Visit the Government Schemes page, search for PM-KISAN, and click View Details. The page shows step-by-step application process. You can apply at nearest CSC or Agriculture Department with your Aadhaar and land documents.'},
  {q:'How is the profit calculated?', a:'Go to Profit Calculator, enter your revenue (quantity sold × price per quintal) for each crop and the total expenses automatically pulled from your expense records. Net Profit = Revenue - Expenses.'},
  {q:'How do I add my crops?', a:'Go to Crop Planner → Add Crop tab. Select crop type, enter area, planting date, and expected harvest date. Your crop will appear in My Crops with growth stage tracking.'},
  {q:'What is the Soil Health Card scheme?', a:'It\'s a free government scheme that provides customized fertilizer recommendations based on soil testing. Go to Government Schemes page and search "Soil Health Card" for details and how to apply.'},
  {q:'How do I track my expenses?', a:'Go to Expense Management → Add Expense. Enter the date, category, description, linked crop and amount. All expenses are totaled and shown in charts on the Summary tab.'},
  {q:'Can I export my farm data?', a:'Yes! Go to Reports & Analytics → Export tab, or Settings → Data Management. You can export your expenses, crops, and full farm data as CSV or JSON files.'}
];

// Helper: Sanitize string to prevent XSS attacks
function escapeHtml(str) {
  if (str === null || str === undefined) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

// Helper: get farmer from session
function getCurrentFarmer() {
  try { return JSON.parse(localStorage.getItem('smartfarm_session')); } catch(e) { return null; }
}
function formatCurrency(n) {
  if (n === null || n === undefined || isNaN(n)) return '₹0';
  return '₹' + Number(n).toLocaleString('en-IN', {maximumFractionDigits:0});
}
function formatDate(d) {
  if (!d) return '—';
  const dt = new Date(d);
  if (isNaN(dt)) return d;
  return dt.toLocaleDateString('en-IN', {day:'2-digit', month:'short', year:'numeric'});
}
function daysDiff(a, b) {
  return Math.round((new Date(b) - new Date(a)) / 86400000);
}
function timeAgo(ts) {
  const s = Math.floor((Date.now() - ts) / 1000);
  if (s < 60) return 'just now';
  if (s < 3600) return Math.floor(s/60) + 'm ago';
  if (s < 86400) return Math.floor(s/3600) + 'h ago';
  return Math.floor(s/86400) + 'd ago';
}
function openModal(html) {
  document.getElementById('modal-container').innerHTML = html;
}
function closeModal() {
  document.getElementById('modal-container').innerHTML = '';
}
function showToast(msg, type='success') {
  const t = document.createElement('div');
  t.className = 'toast toast-' + type;
  t.textContent = msg;
  document.body.appendChild(t);
  setTimeout(() => t.classList.add('show'), 10);
  setTimeout(() => { t.classList.remove('show'); setTimeout(()=>t.remove(),300); }, 3000);
}
function tabs(containerId, defaultTab) {
  const btns = document.querySelectorAll(`#${containerId} .tab-btn`);
  const contents = document.querySelectorAll(`#${containerId} .tab-content`);
  btns.forEach(b => b.addEventListener('click', function() {
    btns.forEach(x=>x.classList.remove('active'));
    contents.forEach(x=>x.classList.remove('active'));
    this.classList.add('active');
    const t = document.getElementById(this.dataset.tab);
    if (t) t.classList.add('active');
  }));
  if (defaultTab) {
    const d = document.querySelector(`#${containerId} [data-tab="${defaultTab}"]`);
    if (d) d.click();
  } else if (btns.length > 0) btns[0].click();
}
function getGrowthStage(plantingDate, duration) {
  const daysGrown = daysDiff(plantingDate, new Date().toISOString().split('T')[0]);
  if (daysGrown < 0) return {stage:'Not Started', pct:0};
  const pct = Math.min(100, Math.round((daysGrown / duration) * 100));
  if (pct >= 100) return {stage:'Harvested/Ready', pct:100};
  if (pct < 20)   return {stage:'Germination', pct};
  if (pct < 40)   return {stage:'Vegetative', pct};
  if (pct < 60)   return {stage:'Flowering', pct};
  if (pct < 80)   return {stage:'Grain Filling', pct};
  return {stage:'Maturity', pct};
}
function destroyChart(id) {
  const existing = Chart.getChart(id);
  if (existing) existing.destroy();
}
